In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# My first Neural Network

 Galaxies vs quasars (but with neural networks) Go back to our SDSS data we've used in Lecture 19. We had color differences, and the task was to classifty quasars vs galaxies. Repeat that task with a neural network.


## Tasks:

Remember: scale your data appropriately

Decide on a testing strategy (a simple test/train split? a CV strategy? set a test set aside to be looked at at the very end?)

Decide your optimization metric.

Write down your network architecture. You can start from a fully connected, multi-layer perceptron (and then explore)

Use one the package among those we've seen. These include Tensorflow via keras, pytorch, and the MPL classifier implemented in scikit-learn. This is an opportunity to pick the one you're most interested in learning.

Optimize the hyperparameters of your network. Explore different hyperparameters and see what fits the data best. Do your best now to optimize the network architecture. Be creative!

Report on the perfomance of the network on the test set; report other metrics that have not been optimized.

In [3]:
data = pd.read_csv('..\solutions\galaxyquasar.csv')

In [4]:
data

,u,g,r,i,z,class,z1,zerr
0,18.97213,18.53676,18.58280,18.34936,18.29215,QSO,0.522819,0.000155
1,19.24592,17.47646,16.47817,16.04472,15.68851,GALAXY,0.122846,0.000028
2,19.43536,17.70268,16.91565,16.58327,16.39128,GALAXY,0.000000,0.000000
3,19.31626,18.18312,17.39591,16.94549,16.65395,GALAXY,0.147435,0.000009
4,19.28828,19.11188,18.88937,18.80013,18.49183,QSO,2.011455,0.000631
...,...,...,...,...,...,...,...,...
49995,19.37295,18.12382,17.39886,16.98503,16.70585,GALAXY,0.113016,0.000011
49996,18.52021,16.88262,16.03280,15.56884,15.22454,GALAXY,0.085063,0.000014
49997,18.62718,17.30876,16.87371,16.62399,16.42296,GALAXY,0.054429,0.000008
49998,19.55140,18.27711,17.62101,17.21947,17.03347,GALAXY,0.112571,0.000009
49999,18.80772,17.75751,17.40500,17.21650,17.12295,GALAXY,0.043652,0.000007

In [5]:
data['u-g']= data['u']-data['g']
data['g-r']= data['g']-data['r']
data['r-i']= data['r']-data['i']
data['i-z']= data['i']-data['z']

classes = np.loadtxt('..\solutions\galaxyquasar.csv', delimiter =',', usecols=5, dtype=str, skiprows=1)
index = np.where(classes=='QSO')
types = np.zeros(len(data['class'])).astype(int)
types[index]=1
data['type']= types

In [6]:
data

,u,g,r,i,z,class,z1,zerr,u-g,g-r,r-i,i-z,type
0,18.97213,18.53676,18.58280,18.34936,18.29215,QSO,0.522819,0.000155,0.43537,-0.04604,0.23344,0.05721,1
1,19.24592,17.47646,16.47817,16.04472,15.68851,GALAXY,0.122846,0.000028,1.76946,0.99829,0.43345,0.35621,0
2,19.43536,17.70268,16.91565,16.58327,16.39128,GALAXY,0.000000,0.000000,1.73268,0.78703,0.33238,0.19199,0
3,19.31626,18.18312,17.39591,16.94549,16.65395,GALAXY,0.147435,0.000009,1.13314,0.78721,0.45042,0.29154,0
4,19.28828,19.11188,18.88937,18.80013,18.49183,QSO,2.011455,0.000631,0.17640,0.22251,0.08924,0.30830,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,19.37295,18.12382,17.39886,16.98503,16.70585,GALAXY,0.113016,0.000011,1.24913,0.72496,0.41383,0.27918,0
49996,18.52021,16.88262,16.03280,15.56884,15.22454,GALAXY,0.085063,0.000014,1.63759,0.84982,0.46396,0.34430,0
49997,18.62718,17.30876,16.87371,16.62399,16.42296,GALAXY,0.054429,0.000008,1.31842,0.43505,0.24972,0.20103,0
49998,19.55140,18.27711,17.62101,17.21947,17.03347,GALAXY,0.112571,0.000009,1.27429,0.65610,0.40154,0.18600,0
49999,18.80772,17.75751,17.40500,17.21650,17.12295,GALAXY,0.043652,0.000007,1.05021,0.35251,0.18850,0.09355,0

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.data as torchdata

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

SyntaxError: invalid syntax (1955197235.py, line 2)